rl-institut/smooth

.travis.yml
tests/test_requirements.txt

A `.travis.yml` already existed but it just contained linters. This PR updates the build config with installation instructions for all smooth dependencies and a final call to pytest.
This should help with https://github.com/rl-institut/smooth/issues/45

Include tests in Travis build config

---

README.md

Fixed some warnings by mdl:
https://github.com/markdownlint/markdownlint
Mostly trailing whitespace and some consistency issues.

README: Fix some Markdown lints

---

.travis.yml
README.md

The oemof structure changed and thus the name of the oemof/oemof to oemof/oemof-solph
Related #65

Fix travis with changed oemof repository

---

smooth/framework/functions/functions.py
smooth/framework/functions/plot_interactive_results.py
smooth/framework/functions/plot_results.py
smooth/framework/run_smooth.py

This PR is moving code from run_smooth to a separate function. Namely the code for the conversion of components description into components as smooth-objects.
(+ last two commit) More over smaller unrelated improvements on error catching and initialization.

Create component objects in a function

---

requirements.txt
smooth/optimization/run_optimization.py

Using a different pickler (dill instead of native pickle) to hand over optimization functions (lambdas) to Pool workers. Updated requirements, but dill may already be required by other packages and therefore present.
Fix #104

fix: lambda pickling under windows with dill

---

smooth/examples/run_smooth_example.py

Added ```__name__ == 'main'``` check to prevent accidental script execution (e.g. when generating docs).
Fix #116

Fix run_smooth_example

---

smooth/optimization/run_optimization.py

When exceeding retries to generate new children, the number of newly generated individuals get printed to console.
Also, when generating the first child generation, not enough parents may have been left in the population (need at least two for sampling). This is now printed to console as well for better debugging.
Fix #136

improved console feedback when aborting

---

smooth/framework/run_smooth.py

Only get results_dict and df_results when show_debug_flag is set. These variables are not used elsewhere.
See also: #3

Speed up run_smooth

---

smooth/optimization/run_optimization.py

When parameter 'ignore_zero' is set, components with an attribute value of zero are ignored in the current model. Defaults to False.

Add opt param to control behavior of attribute with zero value

---

smooth/optimization/run_optimization.py

With this option set, intermediate results are written into a pickle file after each generation and during gradient ascent (post-processing).
The content is the same as from framework.functions.save_results.py, so it can be unpickled by using framework.functions.load_results.py.
Only the two most recent files are retained. All intermediate files are deleted after the optimization ends.
Fix #169

add 'save_intermediate_results' option to GA parameters

---

smooth/optimization/run_optimization.py

Fix #170 
During gradient ascent, new children are only created for parents that  still have improvement potential. Any empty slots in the population short of n_cores are filled up by the same children with multiples in their step size. This effectively checks parents multiple steps ahead during the same generation, instead of only one step ahead.

changed population creation in gradient ascent

---

smooth/framework/functions/plot_results.py

Interval time was set statically to 60 minutes. This simulation parameter is now retrieved from the smooth result and the time axis scaled accordingly.
See also #159

fix time axis in plot_smooth_results

---

smooth/components/component_electrolyzer_waste_heat.py
smooth/components/component_fuel_cell_chp.py
smooth/components/component_gas_engine_chp_biogas.py
smooth/components/component_h2_chp.py
smooth/components/component_pem_electrolyzer.py

Having two components that add custom constraints to the model no longer replaces the other constraint, which led to pyomo complaining. The name of the component is appended to the constraint attribute, making it unique within the model.
Fix #185

include component name in custom constraints

---

.travis.yml
doc/requirements.txt
doc/source/getting_started.rst
requirements.txt
setup.py

It's possible to specify a specific commit of another repository as a dependency for pip. This PR uses this features to add oemof to our requirements.txt. This should simplify the installation of smooth until our changes are merged into a proper release of oemof-solph.
I failed to also include the special oemof dependency into setup.py

Simplify installation of dependencies

---

smooth/examples/run_optimization_example.py

I added the parameter 'ignore_tero' to the example file of the optimization with a short explanation

Add ignore_zero to optimization example

---

smooth/components/component.py
smooth/components/component_battery.py
smooth/components/component_energy_demand_from_csv.py
smooth/components/component_energy_source_from_csv.py
smooth/components/component_sink.py
smooth/components/component_supply.py
smooth/examples/example_plotting_dicts.py

The interval time can now be adjusted, solving issues #159 and #152
This PR is the third of three to split PR #180 into manageable parts.
The components 
- component.py
- component_battery.py
- component_sink.py
- component_supply.py
- component_energy_demand_from_csv.py 
- component_energy_source_from_csv.py 
and the file 
- example_plotting_dicts.py
have been corrected. 
The underlying idea is, that all flows in oemof are designed as time dependent (like Power: [W] or [kW] or material flow per hour [kg/h]) and automatically adjusted to the intervaltime. Until now flows in smooth have been written as if they were interpreted in absolute values (like Energy: [Wh] or [kWh] respectivels [kg]). This commit changes this for the mentioned files, (all?) other components will have to be changed …

Make interval time adjustable

---

smooth/components/component_energy_source_from_csv.py

Small PR to change the default CSV separator to be ',' for all components (only energy_source_from_csv needed changing).
The examples in SMOOTH have been checked and all are working with this change, but any model definitions created outside of SMOOTH prior to this PR might need modification.

changed default csv separator in energy_source_from_csv

---

smooth/components/component.py
smooth/components/component_battery.py
smooth/components/component_compressor_h2.py
smooth/components/component_electrolyzer.py
smooth/components/component_electrolyzer_waste_heat.py
smooth/components/component_fuel_cell_chp.py
smooth/components/component_gas_engine_chp_biogas.py
smooth/components/component_h2_chp.py
smooth/components/component_h2_refuel_cooling_system.py
smooth/components/component_pem_electrolyzer.py
smooth/components/component_storage_h2.py
smooth/components/component_stratified_thermal_storage.py
smooth/components/component_trailer_gate.py
smooth/components/component_trailer_h2_delivery.py
smooth/components/component_trailer_h2_delivery_single.py
smooth/components/external_component.py
smooth/components/external_component_h2_dispenser.py
smooth/framework/run_smooth.py

This PR replaces former outdated PR #209
- within all components replace sim_params by self.sim_params
- remove sim_params as additional parameter of update functions
- incorporate remark from PR #209
- make flake happy
skript executed within component folder:
for f in *.py; do 
sed -i 's/sim_params/self.sim_params/g' $f;
sed -i 's/self.self.sim_params/self.sim_params/g' $f;
sed -i 's/param self.sim_params/param sim_params/g' $f;
sed -i 's/type self.sim_params/type sim_params/g' $f;
sed -i 's/, self.sim_params//g' $f;
sed -i 's/self.sim_params,//g' $f;
sed -i '/sim_params:/d' $f;
done
autopep8 -i --max-line-length 100 -a -a *

Fix/redundant sim params (updated)

---

smooth/components/component_ac_dc_converter.py
smooth/components/component_dc_ac_inverter.py

Given input parameter of AC/DC converter was not set during instance creation, making it use only the default parameters. Model creation was impossible.

set input params of AC/DC converter on init

---

smooth/components/component.py
smooth/components/component_trailer_gate.py
smooth/framework/run_smooth.py

removed unused 'results' input parameter from:
- Generic component (update_var_costs and update_var_emissions functions)
- Trailer gate component (update_var_costs function)
- Run smooth function (instances of the update_var_costs and update_var_emissions functions)

removed unecessary results input param from function

---

smooth/components/component_ac_dc_converter.py
smooth/components/component_dc_ac_inverter.py
smooth/examples/example_model_electrical_components_ACDC.py
smooth/examples/run_smooth_example.py

The components component_ac_dc_converter.py and component_dc_ac_inverter.py  had typos in their definitions that prevented them from running. I changed the typos and added an example file as decided in #231 .

fix components DC_AC_Inverter and AC_DC_Converter and add example file

---

smooth/examples/run_smooth_example.py
smooth/framework/functions/plot_results.py

When an interactive backend is used in Matplotlib, the plt.show() does not prevent the program from continuing, you have to add 
plt.show(block=True)
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.show.html
solves #244

add blocking to show plot in order to plot busses individually

---

.github/workflows/pythonpackage.yml

Most CI fails are caused by flake8 violations. By running flake8 as soon
as possible we can save valuable time ⏱!

CI: Run flake8 ASAP

---

doc/source/smooth.components.rst
smooth/components/component_air_source_heat_pump.py
smooth/components/component_battery.py
smooth/components/component_compressor_h2.py
smooth/components/component_electric_heater.py
smooth/components/component_electrolyzer.py
smooth/components/component_electrolyzer_waste_heat.py
smooth/components/component_energy_demand_from_csv.py
smooth/components/component_energy_source_from_csv.py
smooth/components/component_fuel_cell_chp.py
smooth/components/component_gas_engine_chp_biogas.py
smooth/components/component_gate.py
smooth/components/component_h2_chp.py
smooth/components/component_h2_refuel_cooling_system.py
smooth/components/component_pem_electrolyzer.py
smooth/components/component_power_converter.py
smooth/components/component_sink.py
smooth/components/component_storage_h2.py
smooth/components/component_stratified_thermal_storage.py
smooth/components/component_supply.py
smooth/components/component_trailer_gate.py
smooth/components/component_trailer_gate_cascade.py
smooth/components/component_trailer_h2_delivery.py
smooth/components/component_trailer_h2_delivery_cascade.py
smooth/components/component_trailer_h2_delivery_single.py
smooth/framework/run_smooth.py
tests/test_power_converter.py
tests/test_var_grid.py

Every component now implements add_to_oemof_model instead of create_oemof_model. A solph EnergySystem is required.
In the function, the oemof component is created as before, added to the given energy system and returned. In case of more complex components, a tuple may be returned.
Added docstrings and changed documentation to reflect changes.

Change create_oemof_model to add_to_oemof_model for each component

---

smooth/optimization/run_optimization.py
tests/test_optimization.py

* quantization uses new value instead of old value
*  sigma is always float, even if value is integer

Fix mutate function in run_optimization
