rl-institut/smooth

.gitignore
A really small but quality-of-life change!
=> Ignore VIM swap files

smooth/framework/run_smooth.py
=> Fix off-by-one interval index print

.travis.yml, smooth/examples/example_model.py
run_smooth_example.py was broken. This PR should fix it and add it to travis.yml to detect future breakage earlier.
=> Fix run_smooth_example and check with travis

smooth/examples/example_dict_model.py
CSV paths should be relative.
Fixes https://github.com/rl-institut/smooth/issues/70
=> Fix paths in example_dict_model.py

.travis.yml, README.md
=> Let Travis checkout oemof stable commit

CHANGELOG.md, doc/source/conf.py, setup.py
=> Release 0.2.0

CHANGELOG.md
Unreleased changes can be added to this section that is renamed on each release.
=> Add unreleased section to changelog

smooth/optimization/run_optimization.py
=> Optimization: re-enable val_step

smooth/examples/run_smooth_example.py, smooth/optimization/run_optimization.py
* fitness is computed if there is at least one new configuration (instead of simply aborting when population is not full)
* only create population_size new children maximum
* catch rare error when less than two parents remain
* start new children list instead of copying population
=>  run_optimization improvements

smooth/components/component_gate.py
adde max input value for the gate so we can limit an input.
=> added max input value

requirements.txt
=> pin pyutilib to 5.8.0 for oemof v0.3.3

smooth/optimization/run_optimization.py
Hover over points in plot_results window to show details about individuals, including attributes and objective values. Works during computation and afterwards.
Fix #20
=> mouseover info in optimization plot

smooth/examples/run_optimization_example.py, smooth/optimization/run_optimization.py
Added ```post_processing``` parameter. When set, the results from the genetic algorithm are improved further by tweaking each attribute separately towards a local optimum.
How to use: add ```'post_processing': True``` to _ga_params_ (where population_size etc. is set).
=> Add gradient ascent after optimization

smooth/optimization/run_optimization.py
When a component reaches a zero value during optimization, it is removed from the model.
=> remove component from model during optimization when AV is zero

.github/workflows/pythonpackage.yml, smooth/optimization/run_optimization.py, tests/test_optimization.py
Added basic tests for functions in run_optimization, in the spirit of #35. This led to minor fixes.
=> add basic tests for optimization functions

smooth/optimization/run_optimization.py, tests/test_optimization.py
=> Fix: double model update on ignore_zero

smooth/framework/functions/functions.py
=> fix overwriting of component names during plot_smooth_result

smooth/framework/functions/load_results.py, smooth/framework/functions/save_results.py
- use with...open for better file handling
- rewritten function comments as docstrings
=> reworked save_results and load_results

smooth/examples/run_optimization_example.py
=> added intermediate results

smooth/framework/functions/update_fitted_cost.py
enables a previously calculated 'cost' value to be used as a free variable in the polynomial function
=> possibility of addition of functions

setup.py
This PR includes a change by https://github.com/morrme, updates their branch and adds some classifiers to setup.py for better machine-readability of metadata for this library.
Closes #157
=> Specify license in setup.py

smooth/examples/example_model.py
The example_model  hasn't been up to date with the newest changest in #210 
This is done by this PR
=> update example_model to comply with #210

README.md, setup.py
`setup.py` failed at reading `README.md` if the local standard encoding
is not UTF-8.
Fix #224
=> Fix decoding issue in setup.py

smooth/components/component_trailer_gate.py, smooth/examples/example_model_trailer.py, smooth/examples/example_plotting_dicts.py
flake8 smooth tests doc/source *.py found some errors.
I fixed all of them but one, which seems a false error: 
`smooth\framework\functions\save_important_parameters.py:119:35: E741 ambiguous variable name 'l'`
`l` in this case is a keyword argument and can't be altered.
=> correct small flake8 issues

.github/workflows/pythonpackage.yml
This PR updates our GitHub CI workflow so that it runs all tests and exits with an error if something fails or is not nicely formatted.
=> Update GitHub CI workflow
